### PR TITLE
Be able to pass credentials through ENV variables

### PR DESCRIPTION
**Pull request by molefrog**
As described in #1

### CODE REVIEW

**Comment by ex3ndr** [comment]
Please, make them optional than for backward compatibility!

**Comment by molefrog** [comment]
If you don’t specify them the default `user:password` will be used. See Dockerfile. But I’m not sure if it will work, could you please check?

**Comment by molefrog** [comment]
Hey @ex3ndr could you please check the PR again? We have a situation here in Russia (they started to block telegram servers, so yeah kinda emergency haha). I have few people emailing me already asking how to set up the custom username/password pair.

What I meant in my previous comment: there is already `ENV SOCKS_USER=user` line in `Dockerfile`, so if you don't override it dynamically during run, the default one will be used. Does it sound ok?

**Comment by molefrog** [comment]
@ex3ndr Thanks! 👍

**Pull request merged**
